import type { CourseDefinition } from "./types";

export const reactCourse: CourseDefinition = {
  key: "react",
  slug: "react",
  icon: "⚛️",
  gradient: "linear-gradient(135deg, var(--color-react-blue), var(--color-accent-violet))",
  accentColor: "var(--color-react-blue)",
  featuredTags: ["componentBasics", "hooks", "stateManagement", "rendering"],
  sections: [
    {
      key: "componentBasics",
      icon: "🧩",
      colorVar: "var(--color-accent-cyan-bright)",
      slug: "component-basics",
      ready: true,
      topics: ["JSX", "Props vs State", "Conditional Rendering", "Composition"],
    },
    {
      key: "rendering",
      icon: "🖼️",
      colorVar: "var(--color-accent-violet)",
      slug: "rendering",
      ready: true,
      topics: [
        "Component Lifecycle",
        "Lists & Keys",
        "Render Props",
        "Refs",
        "Events",
      ],
    },
    {
      key: "hooks",
      icon: "🪝",
      colorVar: "var(--color-accent-green)",
      slug: "hooks",
      ready: true,
      topics: [
        "useState",
        "useEffect",
        "useRef",
        "useMemo",
        "useContext",
        "Custom Hooks",
      ],
    },
    {
      key: "stateManagement",
      icon: "🗄️",
      colorVar: "var(--color-accent-orange)",
      slug: "state-management",
      ready: true,
      topics: ["Context", "Zustand", "Jotai", "MobX"],
    },
    {
      key: "routers",
      icon: "🧭",
      colorVar: "var(--color-accent-pink)",
      slug: "routers",
      ready: true,
      topics: ["React Router", "Tanstack Router"],
    },
    {
      key: "writingCss",
      icon: "🎨",
      colorVar: "var(--color-accent-teal)",
      slug: "writing-css",
      ready: true,
      topics: ["CSS Modules", "Tailwind CSS", "Panda CSS"],
    },
    {
      key: "componentLibraries",
      icon: "📦",
      colorVar: "var(--color-accent-purple)",
      slug: "component-libraries",
      ready: true,
      topics: ["Material UI", "Shadcn UI", "Chakra UI"],
    },
    {
      key: "apiCalls",
      icon: "🌐",
      colorVar: "var(--color-accent-teal-deep)",
      slug: "api-calls",
      ready: true,
      topics: ["Axios", "react-query", "SWR", "Apollo", "RTK Query"],
    },
    {
      key: "forms",
      icon: "📝",
      colorVar: "var(--color-accent-orange-strong)",
      slug: "forms",
      ready: true,
      topics: ["React Hook Form", "Formik"],
    },
    {
      key: "testing",
      icon: "🧪",
      colorVar: "var(--color-accent-lime)",
      slug: "testing",
      ready: true,
      topics: ["Vitest", "Jest", "Cypress", "Playwright"],
    },
    {
      key: "typesValidation",
      icon: "🔒",
      colorVar: "var(--color-accent-blue)",
      slug: "types-validation",
      ready: true,
      topics: ["TypeScript", "Zod"],
    },
    {
      key: "frameworks",
      icon: "🏗️",
      colorVar: "var(--color-accent-purple-deep)",
      slug: "frameworks",
      ready: true,
      topics: ["Next.js", "Astro", "react-router"],
    },
    {
      key: "advancedTopics",
      icon: "🚀",
      colorVar: "var(--color-accent-red)",
      slug: "advanced-topics",
      ready: true,
      topics: ["Suspense", "Portals", "Error Boundaries", "Server APIs"],
    },
    {
      key: "animation",
      icon: "✨",
      colorVar: "var(--color-accent-amber)",
      slug: "animation",
      ready: true,
      topics: ["Framer Motion", "react-spring", "GSAP"],
    },
    {
      key: "mobile",
      icon: "📱",
      colorVar: "var(--color-accent-teal)",
      slug: "mobile",
      ready: true,
      topics: ["React Native"],
    },
  ],
};
